---
server:
  port: 8080

config:
  server:
    port: 8888

spring:
  application:
    name: spring-boot-config
  cloud:
    config:
      uri: http://localhost:${config.server.port}
#  profiles:
#    active: prod

# java -jar <name-of-the-jar> --spring.profiles.active=test

app:
  name: ${spring.application.name}

my:
  greeting: Hello, welcome to ${app.name}
  list:
    values: One,Two,Three

db:
  host: 127.0.0.1
  port: 3306
  connection: "{connectionString: 'https://${db.host}:${db.port}', username:
    'foo', password: 'bar'}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
